# Generated by Django 4.1.7 on 2023-04-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="Recipients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(default="", max_length=70)),
                ("login_name", models.CharField(default="", max_length=70)),
                ("name", models.CharField(default="", max_length=30)),
                ("surname", models.CharField(default="", max_length=30)),
                ("phone_number", models.CharField(default="", max_length=20)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("disabilities", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Volunteers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_name", models.CharField(default="", max_length=30)),
                ("name", models.CharField(default="", max_length=30)),
                ("surname", models.CharField(default="", max_length=30)),
                ("phone_number", models.CharField(default="", max_length=70)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.CharField(default="", max_length=70)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("comment", models.CharField(default="", max_length=2000)),
                ("photo", models.ImageField(blank=True, upload_to="requests_images/")),
                ("regular", models.BooleanField(default=False)),
                ("status", models.CharField(default="", max_length=70)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.categories"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relatives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=30)),
                ("surname", models.CharField(default="", max_length=30)),
                ("disabilities", models.BooleanField(default=False)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.recipients"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(default="", max_length=2000)),
                ("photo", models.ImageField(blank=True, upload_to="feedback_images/")),
                ("range", models.CharField(default="", max_length=70)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.requests"
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.volunteers"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(default="", max_length=70)),
                ("city", models.CharField(default="", max_length=70)),
                ("street", models.CharField(default="", max_length=100)),
                ("building", models.IntegerField(blank=True, null=True)),
                ("apartment", models.IntegerField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.recipients"
                    ),
                ),
            ],
        ),
    ]
