# Generated by Django 4.1.7 on 2023-04-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("welcome_message", models.TextField(default="")),
                ("call_for_registration_message", models.TextField(default="")),
                ("choice_message", models.TextField(default="")),
                ("deletion_message", models.TextField(default="")),
                ("call_for_phone_message", models.TextField(default="")),
                ("call_for_name_surname_message", models.TextField(default="")),
                ("call_for_bday_message", models.TextField(default="")),
                ("call_for_address_message", models.TextField(default="")),
                ("call_for_email_message", models.TextField(default="")),
                ("successful_registration_message", models.TextField(default="")),
                ("select_category_message", models.TextField(default="")),
                ("request_help_comment_message", models.TextField(default="")),
                ("save_request_message", models.TextField(default="")),
                ("request_status_notification_message", models.TextField(default="")),
                ("receiving_help_comment_message", models.TextField(default="")),
                ("select_help_or_my_requests", models.TextField(default="")),
            ],
            options={
                "verbose_name": "Messages",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Address"},
        ),
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Categories", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="feedbacks",
            options={"verbose_name": "Feedbacks", "verbose_name_plural": "Feedbacks"},
        ),
        migrations.AlterModelOptions(
            name="recipients",
            options={"verbose_name": "Recipients", "verbose_name_plural": "Recipients"},
        ),
        migrations.AlterModelOptions(
            name="relatives",
            options={"verbose_name": "Relatives", "verbose_name_plural": "Relatives"},
        ),
        migrations.AlterModelOptions(
            name="requests",
            options={"verbose_name": "Requests", "verbose_name_plural": "Requests"},
        ),
        migrations.AlterModelOptions(
            name="volunteers",
            options={"verbose_name": "Volunteers", "verbose_name_plural": "Volunteers"},
        ),
        migrations.AddField(
            model_name="feedbacks",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bot.recipients",
            ),
        ),
        migrations.AddField(
            model_name="requests",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bot.recipients",
            ),
        ),
        migrations.AddField(
            model_name="requests",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bot.volunteers",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bot.recipients",
            ),
        ),
        migrations.AlterField(
            model_name="feedbacks",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bot.requests",
            ),
        ),
        migrations.AlterField(
            model_name="feedbacks",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bot.volunteers",
            ),
        ),
        migrations.AlterField(
            model_name="relatives",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bot.recipients",
            ),
        ),
        migrations.AlterField(
            model_name="requests",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bot.categories",
            ),
        ),
    ]
