# Generated by Django 4.1.7 on 2023-05-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0008_subcategories_requests_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategories",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bot.categories",
            ),
        ),
    ]
