# Generated by Django 4.1.7 on 2023-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0009_alter_subcategories_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subcategories",
            name="index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
